nginx:
  build: ./docker/nginx/
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - php

php:
  build: ./docker/php/
  expose:
    - 9000
  links:
    - mysql
  volumes:
    - .:/var/www/html
  env_file:
    - 'mysql.env'

mysql:
  image: mysql:5.7
  volumes_from:
    - data
  env_file:
    - 'mysql.env'

data:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  command: "true"

phpmyadmin:
  image: adminer
  ports:
    - 8080:8080
  links:
    - mysql