<?php 
use WTSA1\Models\Category;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/public/css/style.css">
    <title>Tagebuch - Tagebucheintrag erstellen</title>
</head>
<body>
    <h1>Eintrag schreiben</h1>
    <a href="/">Zurück</a>

    <?php if (isset($this->data['error'])) { ?>
        <pre class="error"><?= $this->data['error']; ?></pre>
    <?php } ?>

    <form action="/create" method="POST">
        <label for="publish_date">Veröffentlichungsdatum:</label>
        <input type="date" name="publish_date" value="<?= date('Y-m-d') ?>">
        <br>
        <label for="category">Kategorie:</label>
        <select name="category">
            <?php foreach (Category::getAll() as $category) { ?>
                <option value="<?= $category->getId() ?>"><?= $category->getCategory() ?></option>
            <?php } ?>    
        </select>
        <br>
        <label for="content">Inhalt:</label>
        <textarea name="content" cols="60" rows="20" maxlength="1000"></textarea>
        <br>
        <input type="submit" value="Erstellen">
    </form>
</body>
</html>
