<?php 
use WTSA1\Models\Category;
?>

<h1 class="create-title">Eintrag schreiben</h1>
<div class="create-back">
    <a class="call-to-action" href="/">&laquo; Zurück</a>
</div>

<form class="create-form" action="/create" method="POST" enctype="multipart/form-data">
    <div class="create-row">
        <div class="create-col">
            <label for="publish_date">Datum</label>
        </div>
        <div class="create-col">
            <input type="date" name="publish_date" value="<?= date('Y-m-d') ?>">
        </div>
    </div>

    <div class="create-row">
        <div class="create-col">
            <label for="category">Kategorie</label>
        </div>
        <div class="create-col">
            <select name="category">
                <?php foreach (Category::getAll() as $category) { ?>
                    <option value="<?= $category->getId() ?>"><?= $category->getCategory() ?></option>
                <?php } ?>    
            </select>
        </div>
    </div>

    <div class="create-row">
        <div class="create-col">
            <label for="content">Inhalt</label>
        </div>
        <div class="create-col">
            <textarea name="content" maxlength="1000"></textarea>
        </div>
    </div>

    <div class="create-row">
        <div class="create-col">
            <label for="content">Bild</label>
        </div>
        <div class="create-col">
            <input type="file" name="image" accept="image/png,image/jpeg">
        </div>
    </div>

    <div class="create-row">
        <div class="create-col">&nbsp;</div>
        <div class="create-col">
            <br />
            <input class="call-to-action" type="submit" value="Erstellen &raquo;">
        </div>
    </div>
</form>

<?php if (isset($this->data['error'])) { ?>
    <pre class="error dark"><?= $this->data['error']; ?></pre>
<?php } ?>
