<div class="diary-logged-in">
    <div class="diary-username">
        <h2><?=t($this->data["user"]->getUsername())?>'s Tagebuch</h2>
    </div>
    <div class="diary-logout">
        <form action="/logout" method="post">
            <input type="submit" value="Tagebuch schliessen →">
        </form>
    </div>
</div>
<div class="diary-contents">
    <div class="diary-create">
        <a href="/create">Eintrag schreiben →</a>
    </div>
    
    <div class="diary-entries">
        <?php if (count($this->data['entries']) == 0) {?>
            <p class="diary-empty">Deinem Tagebuch mangelt es an Abenteuern :/</p>    
        <?php } ?>

        <?php foreach($this->data['entries'] as $entry) { ?>
            <h4>
                <?=t($entry->getFormattedPublishDate())?>
                <span class="diary-category">
                    <?=t($entry->getCategory()->getCategory())?>
                </span>
            </h4>
            <p>
                <?php if ($entry->getImage()) { ?>
                    <img src="<?=$entry->getEncodedImage()?>" alt="">
                <?php } ?>

                <?=t($entry->getContent())?>
            </p>
        <?php } ?>
    </div>
</div>
