<div class="diary-logged-in">
    <div class="diary-username">
        <h2><?=t($this->data["user"]->getUsername())?>'s diary</h2>
    </div>
    <div class="diary-logout">
        <form action="/logout" method="post">
            <input type="submit" value="Close Diary →">
        </form>
    </div>
</div>
<div class="diary-contents">
    <div class="diary-create">
        <a href="/create">Create →</a>
    </div>
    
    <div class="diary-entries">
        <?php if (count($this->data['entries']) == 0) {?>
            <p class="diary-empty">You don't have any entries in your diary yet :/</p>    
        <?php } ?>

        <?php foreach($this->data['entries'] as $entry) { ?>
            <h4><?=t($entry->getFormattedPublishDate())?></h4>
            <p><?=t($entry->getContent())?></p>
        <?php } ?>
    </div>
</div>
