<?php 
use WTSA1\Models\Category;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tagebuch - Bild anschauen</title>

    <style>
        a {
            display: inline-block;
            padding: 2px 0 2px 5px;
            font-family: Arial, sans-serif;
            text-decoration: none;
            color: #FFF;
        }

        body {
            background: #333;
            margin: 0;
            padding: 0;
        }

        img {
            width: 100%;
        }
    </style>
</head>
<body>
    <a href="/">&laquo; Zurück</a>
    <br>

    <?php if (!empty($this->data['error'])) { ?>
        <pre class="error"><?= $this->data['error']; ?></pre>
    <?php } ?>

    <?php if (!empty($this->data['image'])) { ?>
        <img src="<?= $this->data['image'] ?>">
    <?php } ?>
</body>
</html>
