<?php 
use WTSA1\Models\Category;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tagebuch - Bild anschauen</title>
</head>
<body>
    <h1>Bild anschauen</h1>
    <a href="/">Zurück</a>
    <br>

    <?php if (!empty($this->data['error'])) { ?>
        <pre class="error"><?= $this->data['error']; ?></pre>
    <?php } ?>

    <?php if (!empty($this->data['image'])) { ?>
        <img src="<?= $this->data['image'] ?>">
    <?php } ?>
</body>
</html>
