<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/public/css/style.css">
    <title>Login</title>
</head>
<body>
    <h1>Login Page</h1>

    <?php if (isset($this->data['error'])) { ?>
        <pre class="error"><?php echo $this->data['error']; ?></pre>
    <?php } ?>

    <form action="/login" method="POST">
        <label for="username">Username:</label>
        <input type="text" name="username">
        <br>
        <label for="password">Passwort:</label>
        <input type="text" name="password">
        <br>
        <input type="submit" value="Login">
    </form>
</body>
</html>