<div class="diary-content table">
    <div class="diary-auth">
        <h1>Tagebuch öffnen</h1>

        <span>
            (<a href="/register">Tagebuch erstellen →</a>)
        </span>

        <form action="/login" method="POST">
            <input type="text" name="username" value="<?=ta($_REQUEST, "username")?>" placeholder="Username">
            <br>
            <input type="password" name="password" placeholder="Passwort">
            <br>
            <input type="submit" value="Öffnen">
        </form>

        <div class="error"><?=ta($this->data, "error")?></div>
    </div>
</div>
