<div class="diary-content table">
    <div class="diary-auth">
        <h1>Tagebuch erstellen</h1>

        <span>
            <a class="call-to-action" href="/login">← Einloggen</a>
        </span>

        <form action="/register" method="POST">
            <input type="text" name="username" value="<?=ta($_REQUEST, "username")?>" placeholder="Username">
            <br>
            <input type="password" name="password" value="<?=ta($_REQUEST, "password")?>" placeholder="Passwort">
            <br>
            <input type="password" name="passwordrep" value="<?=ta($_REQUEST, "passwordrep")?>" placeholder="Passwort wiederholen">
            <br>
            <input type="submit" value="Erstellen">
        </form>

        <div class="error"><?=ta($this->data, "error"); ?></div>
    </div>
</div>
