
                      <!-- CONTENT END -->

                    </div>
                </div>
                <div class="diary-side">
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidecloser"></div>
                </div>
            </div>
            <div class="diary-bottom">
                <div class="diary-bottom-pages">
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottomcloser"></div>
                </div>
                <div class="diary-bottom-spacer"></div>
                <?php if (isset($GLOBALS['_VERSION_']) && strlen($GLOBALS['_VERSION_']) > 0) { ?>
                    <div class="git-version"><?= $GLOBALS['_VERSION_'] ?></div>
                <?php } ?>
            </div>
        </div>
    </div>
</body>
</html>
