
                      <!-- CONTENT END -->

                    </div>
                </div>
                <div class="diary-side">
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidepage"></div>
                    <div class="diary-sidecloser"></div>
                </div>
            </div>
            <div class="diary-bottom">
                <div class="diary-bottom-pages">
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottompage"></div>
                    <div class="diary-bottomcloser"></div>
                </div>
                <div class="diary-bottom-spacer"></div>
            </div>
        </div>
    </div>
</body>
</html>
