<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="shortcut icon" href="/public/assets/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Caveat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/public/css/style.css">
    
    <title>Simple Diary <?=t($bindings['title'])?></title>
</head>
<body>
    <div class="diary-wrapper">
        <div class="diary-wrapper-inner">
            <div class="diary-wrapper-flex">
                <div class="diary-container">
                    <div class="diary-body">

                      <!-- CONTENT START -->
